#!/usr/bin/env python3
"""
Generate scaled aircraft icons and aircrafts_data.js from aircrafts.csv.

For each aircraft with a source PNG icon:
  1. Crop to content bounding box (remove transparent padding)
  2. Scale to a display size proportional to the aircraft's real-world length
  3. Save to icons/scaled/<slug>.png

Then write data/aircrafts_data.js with window.AIRCRAFT_DATA containing
per-type { type, icon, width, height } for use in app.js.

Usage: python3 scripts/generate-aircraft-icons.py
Requires: Pillow  (pip install Pillow)
"""

import os
import sys
import csv
import re

try:
    from PIL import Image
    import numpy as np
except ImportError:
    print("Error: Pillow and numpy are required. Run: pip install Pillow numpy", file=sys.stderr)
    sys.exit(1)

# ── Configuration ──────────────────────────────────────────────────────────────
# B-29 (longest aircraft) maps to MAX_PX wide on the map icon.
MAX_PX = 52
MAX_FT = 99.0   # B-29 Superfortress fuselage length
MIN_PX = 13     # smallest allowed icon width (very short fighters)

ALPHA_THRESHOLD = 30  # pixels with alpha < this are considered transparent
# ──────────────────────────────────────────────────────────────────────────────

def slugify(s):
    return re.sub(r'[^a-z0-9]+', '_', s.lower()).strip('_')

def crop_to_content(img):
    """Return image cropped to the bounding box of non-transparent pixels."""
    rgba = img.convert('RGBA')
    arr = np.array(rgba)
    alpha = arr[:, :, 3]
    mask = alpha > ALPHA_THRESHOLD
    rows = np.any(mask, axis=1)
    cols = np.any(mask, axis=0)
    if not rows.any():
        return img  # fully transparent, return as-is
    rmin, rmax = int(np.where(rows)[0][0]), int(np.where(rows)[0][-1])
    cmin, cmax = int(np.where(cols)[0][0]), int(np.where(cols)[0][-1])
    return rgba.crop((cmin, rmin, cmax + 1, rmax + 1))

def display_size(length_ft, crop_w, crop_h):
    """Compute (display_w, display_h) proportional to real-world length."""
    w = max(MIN_PX, round((length_ft / MAX_FT) * MAX_PX))
    # Preserve aspect ratio of the cropped source image
    if crop_w > 0:
        h = max(1, round(w * crop_h / crop_w))
    else:
        h = w
    return w, h

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir   = os.path.join(script_dir, '..')
    csv_path   = os.path.join(root_dir, 'data', 'aircrafts.csv')
    scaled_dir = os.path.join(root_dir, 'icons', 'scaled')
    output_js  = os.path.join(root_dir, 'data', 'aircrafts_data.js')

    os.makedirs(scaled_dir, exist_ok=True)

    print(f"Reading {csv_path}")
    rows = []
    with open(csv_path, newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    js_entries = []

    for row in rows:
        aircraft_type = row['type'].strip()
        length_ft     = float(row['length_ft'])
        icon_src      = row['icon_src'].strip()
        slug          = slugify(aircraft_type)

        src_path = os.path.join(root_dir, icon_src) if icon_src else None

        if src_path and os.path.isfile(src_path) and src_path.lower().endswith('.png'):
            # ── Crop source image to its content bounding box ────────────────
            img = Image.open(src_path)
            cropped = crop_to_content(img)
            crop_w, crop_h = cropped.size

            # ── Compute target display size based on real-world length ────────
            disp_w, disp_h = display_size(length_ft, crop_w, crop_h)

            # ── Save cropped+scaled version ───────────────────────────────────
            out_name = f"{slug}.png"
            out_path = os.path.join(scaled_dir, out_name)
            scaled_img = cropped.resize((disp_w, disp_h), Image.LANCZOS)
            scaled_img.save(out_path, 'PNG', optimize=True)

            icon_url = f"icons/scaled/{out_name}"
            needs_invert = icon_src in ('icons/b24.png', 'icons/b25.png',
                                        'icons/b29.png', 'icons/p40_edited.png')
            print(f"  {aircraft_type}: {crop_w}×{crop_h}px crop → {disp_w}×{disp_h}px  ({icon_url})")
        else:
            # No source PNG — use default.svg, size via CSS only
            disp_w, disp_h = display_size(length_ft, 1, 1)  # square default
            icon_url       = 'icons/default.svg'
            needs_invert   = False
            print(f"  {aircraft_type}: no PNG source → default.svg {disp_w}×{disp_h}px")

        js_entries.append({
            'type':        aircraft_type,
            'icon':        icon_url,
            'width':       disp_w,
            'height':      disp_h,
            'needsInvert': 'true' if needs_invert else 'false',
        })

    # ── Write JS ──────────────────────────────────────────────────────────────
    lines = ['// Auto-generated by scripts/generate-aircraft-icons.py',
             'window.AIRCRAFT_DATA = [']
    for e in js_entries:
        lines.append(
            f'  {{type:"{e["type"]}",icon:"{e["icon"]}",width:{e["width"]},'
            f'height:{e["height"]},needsInvert:{e["needsInvert"]}}},'
        )
    lines.append('];')
    js_content = '\n'.join(lines) + '\n'

    with open(output_js, 'w') as f:
        f.write(js_content)

    print(f"\n✓ icons/scaled/ populated with {sum(1 for e in js_entries if e['icon'].startswith('icons/scaled'))} scaled PNGs")
    print(f"✓ data/aircrafts_data.js written ({len(js_entries)} entries)")

if __name__ == '__main__':
    main()
